kind: ConfigMap 
apiVersion: v1
data:
  size: 10Gi
  storageClassName: do-block-storage
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config-artifact-pvc
  namespace: tekton-pipelines



